//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplacePortal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecsFilter
    {
        public int PropertyID { get; set; }
        public int SubcategoryID { get; set; }
        public float MinValue { get; set; }
        public float MaxValue { get; set; }
    
        public virtual tblProperty tblProperty { get; set; }
        public virtual tblSubcategory tblSubcategory { get; set; }
    }
}
